### ISSUE TITLE
Conflict between local/btk_env with nodejs

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/tutorials#1]
At this step [in today's mollusc community tutorial](https://github.com/blobtoolkit/tutorials/blob/main/2021-04-28_blobtoolkit_commandline_mollusc.md), I encountered the following error:

```shell
(btk_env) samb@computer:~/blobtoolkit/viewer$ npm install
internal/options.js:4
const { options, aliases } = getOptions();
                             ^

Error: Cannot create a string longer than 0x3fffffe7 characters
    at internal/options.js:4:30
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at startup (internal/bootstrap/node.js:116:45)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Aborted (core dumped)
```

I was able to resolve the error by removing my local install of nodejs via:

```shell
sudo apt remove npm
sudo apt autoremove
```

Once I did that, I could successfully run the `npm install` step without issue:

```shell
(btk_env) samb@computer:~/blobtoolkit/viewer$ npm install
```

Note: The `sudo apt autoremove` was required to get the conda `btk_env` npm to work.

You may want to move this issue to another repo; I just wasn't sure which one to put this in.

---

Operating system deets:

```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```shell
samb@computer:~/blobtoolkit/viewer$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   45 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       8
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           165
Model name:                      Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
Stepping:                        2
CPU MHz:                         2399.998
BogoMIPS:                        4799.99
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology ts
                                 c_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowpre
                                 fetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves
                                  arat pku ospke md_clear flush_l1d arch_capabilities
```

```shell
samb@computer:~/blobtoolkit/viewer$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           53Gi       1.6Gi        44Gi       240Mi       7.3Gi        51Gi
Swap:         2.0Gi          0B       2.0Gi
```

**Comment by sujaikumar** [comment]
Many thanks for posting that solution! I got as far as suggesting `sudo apt remove npm --purge` but forgot `autoremove`!
